name: synology
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  auto_route: ^5.0.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  injectable: ^2.1.0
  flutter_svg: ^1.1.6
  get_it: ^7.2.0

dev_dependencies:
  auto_route_generator: ^5.0.3
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  injectable_generator: ^2.1.3
  flutter_gen_runner: ^5.1.0+1

  lint: ^2.0.0

flutter_gen:
  integrations:
    flutter_svg: true


flutter:
  generate: true
  uses-material-design: true